backend:
  name: git-gateway
  repo: thischrisblack/shelly-black-website
  branch: main
media_folder: public/images
public_folder: images
publish_mode: editorial_workflow
collections:
  - label: "Photography Blog"
    name: "photo-blog"
    folder: "content/blog"
    create: true
    filter: { field: "category", value: "Photography" }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Published Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY/MM/DD",
          time_format: false,
          format: "YYYY/MM/DD",
          picker_utc: true,
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          default: "../images/photography-default.jpg",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Photography", "Library & Archival Work"],
          default: "Photography",
        }
  - label: "Library & Archival Work Blog"
    name: "Library & Archival Work-blog"
    folder: "content/blog"
    create: true
    filter: { field: "category", value: "Library & Archival Work" }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Published Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY/MM/DD",
          time_format: false,
          format: "YYYY/MM/DD",
          picker_utc: true,
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          default: "../images/library-default.jpg",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Photography", "Library & Archival Work"],
          default: "Library & Archival Work",
        }
  - label: "Gallery"
    name: "gallery"
    folder: "content/galleries"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - {
          label: "Gallery Images",
          name: "galleryImages",
          widget: "list",
          summary: "{{fields.galleryImages}}",
          field: { label: Image, name: image, widget: image },
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
