backend:
  name: git-gateway
  repo: thischrisblack/shelly-black-website
  branch: main
media_folder: public/images
public_folder: images
publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          multiple: true,
          required: true,
          options: ["Library & Archival Work", "Photography", "Internship"],
        }
      - {
          label: "Published Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY/MM/DD",
          time_format: false,
          format: "YYYY/MM/DD",
          picker_utc: true,
        }
      - label: "Image"
        name: "image"
        widget: "object"
        required: true
        fields:
          - { label: "File", name: "src", widget: "image", required: true }
          - { label: "Alt Text", name: "alt", widget: "string", required: true }
      - { label: "Private", name: "private", widget: "boolean", default: false }
      - {
          label: "Gallery Images",
          name: "galleryImages",
          widget: "list",
          summary: "{{fields.galleryImages}}",
          field: { label: Image, name: image, widget: image },
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Gallery"
    name: "gallery"
    folder: "content/galleries"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          required: true,
          options: ["Personal Projects", "Other Work"],
        }
      - label: "Cover Image"
        name: "image"
        widget: "object"
        required: true
        fields:
          - { label: "File", name: "src", widget: "image", required: true }
          - { label: "Alt Text", name: "alt", widget: "string", required: true }
      - {
          label: "Gallery Images",
          name: "galleryImages",
          widget: "list",
          summary: "{{fields.galleryImages}}",
          field: { label: Image, name: image, widget: image },
        }
      - {
          label: "Sort Order",
          name: "sortOrder",
          widget: "number",
          value_types: "int",
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - label: "Pages"
    name: "pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Image"
        name: "image"
        widget: "object"
        required: false
        fields:
          - { label: "File", name: "src", widget: "image", required: true }
          - { label: "Alt Text", name: "alt", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown" }
