backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - label: "Photography Blog"
    name: "photo-blog"
    folder: "content/blog"
    create: true
    filter: { field: "category", value: "Photography" }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Published Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: false,
          format: "'YYYY-MM-DD'",
          picker_utc: true,
        }
      - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Photography", "Library"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Library Blog"
    name: "library-blog"
    folder: "content/blog"
    create: true
    filter: { field: "category", value: "Library" }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Published Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: false,
          format: "'YYYY-MM-DD'",
          picker_utc: true,
        }
      - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Photography", "Library"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Gallery"
    name: "gallery"
    folder: "content/galleries"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - {
          label: "Gallery Images",
          name: "galleryImages",
          widget: "list",
          summary: "{{fields.galleryImages}}",
          field: { label: Image, name: image, widget: image },
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
