backend:
    name: git-gateway
    branch: main
media_folder: public/images
public_folder: images
collections:
  - label: "Blog"
    name: "blog"
    folder: "posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Published Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}